version: "3.9"
services:
  app:
    build: .
    container_name: sgp-app
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./prisma:/app/prisma
      - ./assets:/app/assets
      - ./auth:/app/auth
    restart: unless-stopped
