version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: sgp-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sgp
    ports:
      - "5433:5432"
    volumes:
      - sgp_pg_data:/var/lib/postgresql/data
volumes:
  sgp_pg_data:
